export interface CountryDialCode {
  /** ISO 3166-1 alpha-2, unique key for list rendering. */
  iso: string;
  /** Arabic display name (primary UI language). */
  nameAr: string;
  /** International dial code without the leading "+". */
  dial: string;
  flag: string;
}

/** Derives the regional-indicator flag emoji from an ISO 3166-1 alpha-2 code. */
function flagFromIso(iso: string): string {
  return iso
    .toUpperCase()
    .replace(/[A-Z]/g, (letter) => String.fromCodePoint(127397 + letter.charCodeAt(0)));
}

export const DEFAULT_COUNTRY: CountryDialCode = {
  iso: 'SY',
  nameAr: 'سوريا',
  dial: '963',
  flag: flagFromIso('SY'),
};

interface CountrySeed {
  iso: string;
  nameAr: string;
  dial: string;
}

/**
 * Complete ISO 3166-1 alpha-2 country/territory set, ordered for the primary
 * audience: Arabic-speaking countries first, then key diaspora destinations,
 * then every remaining country alphabetically by ISO code. Search makes the
 * ordering secondary, but it still matters for two reasons:
 *
 * - Discoverability for the core audience.
 * - Dial codes are not unique (`+1` NANP, `+7`, `+44`, `+212`, `+262`, …). When
 *   several entries share a dial code, the first one wins in
 *   `findDialMatch`, so the shared-code country a user is most likely to mean
 *   is listed before its siblings.
 */
const COUNTRY_SEEDS: readonly CountrySeed[] = [
  // Levant, Gulf and the wider Arab world.
  { iso: 'PS', nameAr: 'فلسطين', dial: '970' },
  { iso: 'LB', nameAr: 'لبنان', dial: '961' },
  { iso: 'JO', nameAr: 'الأردن', dial: '962' },
  { iso: 'IQ', nameAr: 'العراق', dial: '964' },
  { iso: 'KW', nameAr: 'الكويت', dial: '965' },
  { iso: 'SA', nameAr: 'السعودية', dial: '966' },
  { iso: 'BH', nameAr: 'البحرين', dial: '973' },
  { iso: 'QA', nameAr: 'قطر', dial: '974' },
  { iso: 'AE', nameAr: 'الإمارات', dial: '971' },
  { iso: 'OM', nameAr: 'عُمان', dial: '968' },
  { iso: 'YE', nameAr: 'اليمن', dial: '967' },
  { iso: 'EG', nameAr: 'مصر', dial: '20' },
  { iso: 'SD', nameAr: 'السودان', dial: '249' },
  { iso: 'LY', nameAr: 'ليبيا', dial: '218' },
  { iso: 'TN', nameAr: 'تونس', dial: '216' },
  { iso: 'DZ', nameAr: 'الجزائر', dial: '213' },
  { iso: 'MA', nameAr: 'المغرب', dial: '212' },
  { iso: 'MR', nameAr: 'موريتانيا', dial: '222' },
  { iso: 'SO', nameAr: 'الصومال', dial: '252' },
  { iso: 'DJ', nameAr: 'جيبوتي', dial: '253' },
  { iso: 'KM', nameAr: 'جزر القمر', dial: '269' },

  // Major diaspora destinations and neighbouring regions.
  { iso: 'TR', nameAr: 'تركيا', dial: '90' },
  { iso: 'IR', nameAr: 'إيران', dial: '98' },
  { iso: 'AZ', nameAr: 'أذربيجان', dial: '994' },
  { iso: 'AM', nameAr: 'أرمينيا', dial: '374' },
  { iso: 'GE', nameAr: 'جورجيا', dial: '995' },
  { iso: 'DE', nameAr: 'ألمانيا', dial: '49' },
  { iso: 'SE', nameAr: 'السويد', dial: '46' },
  { iso: 'NL', nameAr: 'هولندا', dial: '31' },
  { iso: 'BE', nameAr: 'بلجيكا', dial: '32' },
  { iso: 'DK', nameAr: 'الدنمارك', dial: '45' },
  { iso: 'FI', nameAr: 'فنلندا', dial: '358' },
  { iso: 'FR', nameAr: 'فرنسا', dial: '33' },
  { iso: 'GB', nameAr: 'المملكة المتحدة', dial: '44' },
  { iso: 'ES', nameAr: 'إسبانيا', dial: '34' },
  { iso: 'IT', nameAr: 'إيطاليا', dial: '39' },
  { iso: 'GR', nameAr: 'اليونان', dial: '30' },
  { iso: 'RO', nameAr: 'رومانيا', dial: '40' },
  { iso: 'RU', nameAr: 'روسيا', dial: '7' },
  { iso: 'UA', nameAr: 'أوكرانيا', dial: '380' },
  { iso: 'US', nameAr: 'الولايات المتحدة', dial: '1' },
  { iso: 'CA', nameAr: 'كندا', dial: '1' },
  { iso: 'AU', nameAr: 'أستراليا', dial: '61' },
  { iso: 'MY', nameAr: 'ماليزيا', dial: '60' },
  { iso: 'PK', nameAr: 'باكستان', dial: '92' },
  { iso: 'IN', nameAr: 'الهند', dial: '91' },
  { iso: 'BD', nameAr: 'بنغلاديش', dial: '880' },
  { iso: 'AF', nameAr: 'أفغانستان', dial: '93' },

  // Every remaining country and territory, alphabetical by ISO code.
  { iso: 'AD', nameAr: 'أندورا', dial: '376' },
  { iso: 'AG', nameAr: 'أنتيغوا وبربودا', dial: '1' },
  { iso: 'AI', nameAr: 'أنغويلا', dial: '1' },
  { iso: 'AL', nameAr: 'ألبانيا', dial: '355' },
  { iso: 'AO', nameAr: 'أنغولا', dial: '244' },
  { iso: 'AQ', nameAr: 'أنتاركتيكا', dial: '672' },
  { iso: 'AR', nameAr: 'الأرجنتين', dial: '54' },
  { iso: 'AS', nameAr: 'ساموا الأمريكية', dial: '1' },
  { iso: 'AT', nameAr: 'النمسا', dial: '43' },
  { iso: 'AW', nameAr: 'أروبا', dial: '297' },
  { iso: 'AX', nameAr: 'جزر أولاند', dial: '358' },
  { iso: 'BA', nameAr: 'البوسنة والهرسك', dial: '387' },
  { iso: 'BB', nameAr: 'بربادوس', dial: '1' },
  { iso: 'BF', nameAr: 'بوركينا فاسو', dial: '226' },
  { iso: 'BG', nameAr: 'بلغاريا', dial: '359' },
  { iso: 'BI', nameAr: 'بوروندي', dial: '257' },
  { iso: 'BJ', nameAr: 'بنين', dial: '229' },
  { iso: 'BL', nameAr: 'سان بارتيلمي', dial: '590' },
  { iso: 'BM', nameAr: 'برمودا', dial: '1' },
  { iso: 'BN', nameAr: 'بروناي', dial: '673' },
  { iso: 'BO', nameAr: 'بوليفيا', dial: '591' },
  { iso: 'BQ', nameAr: 'الجزر الكاريبية الهولندية', dial: '599' },
  { iso: 'BR', nameAr: 'البرازيل', dial: '55' },
  { iso: 'BS', nameAr: 'جزر البهاما', dial: '1' },
  { iso: 'BT', nameAr: 'بوتان', dial: '975' },
  { iso: 'BW', nameAr: 'بوتسوانا', dial: '267' },
  { iso: 'BY', nameAr: 'بيلاروسيا', dial: '375' },
  { iso: 'BZ', nameAr: 'بليز', dial: '501' },
  { iso: 'CC', nameAr: 'جزر كوكوس', dial: '61' },
  { iso: 'CD', nameAr: 'الكونغو الديمقراطية', dial: '243' },
  { iso: 'CF', nameAr: 'جمهورية أفريقيا الوسطى', dial: '236' },
  { iso: 'CG', nameAr: 'الكونغو', dial: '242' },
  { iso: 'CH', nameAr: 'سويسرا', dial: '41' },
  { iso: 'CI', nameAr: 'ساحل العاج', dial: '225' },
  { iso: 'CK', nameAr: 'جزر كوك', dial: '682' },
  { iso: 'CL', nameAr: 'تشيلي', dial: '56' },
  { iso: 'CM', nameAr: 'الكاميرون', dial: '237' },
  { iso: 'CN', nameAr: 'الصين', dial: '86' },
  { iso: 'CO', nameAr: 'كولومبيا', dial: '57' },
  { iso: 'CR', nameAr: 'كوستاريكا', dial: '506' },
  { iso: 'CU', nameAr: 'كوبا', dial: '53' },
  { iso: 'CV', nameAr: 'الرأس الأخضر', dial: '238' },
  { iso: 'CW', nameAr: 'كوراساو', dial: '599' },
  { iso: 'CX', nameAr: 'جزيرة كريسماس', dial: '61' },
  { iso: 'CY', nameAr: 'قبرص', dial: '357' },
  { iso: 'CZ', nameAr: 'التشيك', dial: '420' },
  { iso: 'DM', nameAr: 'دومينيكا', dial: '1' },
  { iso: 'DO', nameAr: 'جمهورية الدومينيكان', dial: '1' },
  { iso: 'EC', nameAr: 'الإكوادور', dial: '593' },
  { iso: 'EE', nameAr: 'إستونيا', dial: '372' },
  { iso: 'EH', nameAr: 'الصحراء الغربية', dial: '212' },
  { iso: 'ER', nameAr: 'إريتريا', dial: '291' },
  { iso: 'ET', nameAr: 'إثيوبيا', dial: '251' },
  { iso: 'FJ', nameAr: 'فيجي', dial: '679' },
  { iso: 'FK', nameAr: 'جزر فوكلاند', dial: '500' },
  { iso: 'FM', nameAr: 'ميكرونيزيا', dial: '691' },
  { iso: 'FO', nameAr: 'جزر فارو', dial: '298' },
  { iso: 'GA', nameAr: 'الغابون', dial: '241' },
  { iso: 'GD', nameAr: 'غرينادا', dial: '1' },
  { iso: 'GF', nameAr: 'غيانا الفرنسية', dial: '594' },
  { iso: 'GG', nameAr: 'غيرنزي', dial: '44' },
  { iso: 'GH', nameAr: 'غانا', dial: '233' },
  { iso: 'GI', nameAr: 'جبل طارق', dial: '350' },
  { iso: 'GL', nameAr: 'غرينلاند', dial: '299' },
  { iso: 'GM', nameAr: 'غامبيا', dial: '220' },
  { iso: 'GN', nameAr: 'غينيا', dial: '224' },
  { iso: 'GP', nameAr: 'غوادلوب', dial: '590' },
  { iso: 'GQ', nameAr: 'غينيا الاستوائية', dial: '240' },
  { iso: 'GS', nameAr: 'جورجيا الجنوبية وجزر ساندويتش الجنوبية', dial: '500' },
  { iso: 'GT', nameAr: 'غواتيمالا', dial: '502' },
  { iso: 'GU', nameAr: 'غوام', dial: '1' },
  { iso: 'GW', nameAr: 'غينيا بيساو', dial: '245' },
  { iso: 'GY', nameAr: 'غيانا', dial: '592' },
  { iso: 'HK', nameAr: 'هونغ كونغ', dial: '852' },
  { iso: 'HN', nameAr: 'هندوراس', dial: '504' },
  { iso: 'HR', nameAr: 'كرواتيا', dial: '385' },
  { iso: 'HT', nameAr: 'هايتي', dial: '509' },
  { iso: 'HU', nameAr: 'هنغاريا', dial: '36' },
  { iso: 'ID', nameAr: 'إندونيسيا', dial: '62' },
  { iso: 'IE', nameAr: 'أيرلندا', dial: '353' },
  { iso: 'IL', nameAr: 'إسرائيل', dial: '972' },
  { iso: 'IM', nameAr: 'جزيرة مان', dial: '44' },
  { iso: 'IO', nameAr: 'إقليم المحيط الهندي البريطاني', dial: '246' },
  { iso: 'IS', nameAr: 'آيسلندا', dial: '354' },
  { iso: 'JE', nameAr: 'جيرزي', dial: '44' },
  { iso: 'JM', nameAr: 'جامايكا', dial: '1' },
  { iso: 'JP', nameAr: 'اليابان', dial: '81' },
  { iso: 'KE', nameAr: 'كينيا', dial: '254' },
  { iso: 'KG', nameAr: 'قيرغيزستان', dial: '996' },
  { iso: 'KH', nameAr: 'كمبوديا', dial: '855' },
  { iso: 'KI', nameAr: 'كيريباتي', dial: '686' },
  { iso: 'KN', nameAr: 'سانت كيتس ونيفيس', dial: '1' },
  { iso: 'KP', nameAr: 'كوريا الشمالية', dial: '850' },
  { iso: 'KR', nameAr: 'كوريا الجنوبية', dial: '82' },
  { iso: 'KY', nameAr: 'جزر كايمان', dial: '1' },
  { iso: 'KZ', nameAr: 'كازاخستان', dial: '7' },
  { iso: 'LA', nameAr: 'لاوس', dial: '856' },
  { iso: 'LC', nameAr: 'سانت لوسيا', dial: '1' },
  { iso: 'LI', nameAr: 'ليختنشتاين', dial: '423' },
  { iso: 'LK', nameAr: 'سريلانكا', dial: '94' },
  { iso: 'LR', nameAr: 'ليبيريا', dial: '231' },
  { iso: 'LS', nameAr: 'ليسوتو', dial: '266' },
  { iso: 'LT', nameAr: 'ليتوانيا', dial: '370' },
  { iso: 'LU', nameAr: 'لوكسمبورغ', dial: '352' },
  { iso: 'LV', nameAr: 'لاتفيا', dial: '371' },
  { iso: 'MC', nameAr: 'موناكو', dial: '377' },
  { iso: 'MD', nameAr: 'مولدوفا', dial: '373' },
  { iso: 'ME', nameAr: 'الجبل الأسود', dial: '382' },
  { iso: 'MF', nameAr: 'سان مارتن', dial: '590' },
  { iso: 'MG', nameAr: 'مدغشقر', dial: '261' },
  { iso: 'MH', nameAr: 'جزر مارشال', dial: '692' },
  { iso: 'MK', nameAr: 'مقدونيا الشمالية', dial: '389' },
  { iso: 'ML', nameAr: 'مالي', dial: '223' },
  { iso: 'MM', nameAr: 'ميانمار', dial: '95' },
  { iso: 'MN', nameAr: 'منغوليا', dial: '976' },
  { iso: 'MO', nameAr: 'ماكاو', dial: '853' },
  { iso: 'MP', nameAr: 'جزر ماريانا الشمالية', dial: '1' },
  { iso: 'MQ', nameAr: 'مارتينيك', dial: '596' },
  { iso: 'MS', nameAr: 'مونتسرات', dial: '1' },
  { iso: 'MT', nameAr: 'مالطا', dial: '356' },
  { iso: 'MU', nameAr: 'موريشيوس', dial: '230' },
  { iso: 'MV', nameAr: 'المالديف', dial: '960' },
  { iso: 'MW', nameAr: 'مالاوي', dial: '265' },
  { iso: 'MX', nameAr: 'المكسيك', dial: '52' },
  { iso: 'MZ', nameAr: 'موزمبيق', dial: '258' },
  { iso: 'NA', nameAr: 'ناميبيا', dial: '264' },
  { iso: 'NC', nameAr: 'كاليدونيا الجديدة', dial: '687' },
  { iso: 'NE', nameAr: 'النيجر', dial: '227' },
  { iso: 'NF', nameAr: 'جزيرة نورفولك', dial: '672' },
  { iso: 'NG', nameAr: 'نيجيريا', dial: '234' },
  { iso: 'NI', nameAr: 'نيكاراغوا', dial: '505' },
  { iso: 'NO', nameAr: 'النرويج', dial: '47' },
  { iso: 'NP', nameAr: 'نيبال', dial: '977' },
  { iso: 'NR', nameAr: 'ناورو', dial: '674' },
  { iso: 'NU', nameAr: 'نييوي', dial: '683' },
  { iso: 'NZ', nameAr: 'نيوزيلندا', dial: '64' },
  { iso: 'PA', nameAr: 'بنما', dial: '507' },
  { iso: 'PE', nameAr: 'بيرو', dial: '51' },
  { iso: 'PF', nameAr: 'بولينيزيا الفرنسية', dial: '689' },
  { iso: 'PG', nameAr: 'بابوا غينيا الجديدة', dial: '675' },
  { iso: 'PH', nameAr: 'الفلبين', dial: '63' },
  { iso: 'PL', nameAr: 'بولندا', dial: '48' },
  { iso: 'PM', nameAr: 'سان بيير وميكلون', dial: '508' },
  { iso: 'PN', nameAr: 'جزر بيتكيرن', dial: '64' },
  { iso: 'PR', nameAr: 'بورتوريكو', dial: '1' },
  { iso: 'PT', nameAr: 'البرتغال', dial: '351' },
  { iso: 'PW', nameAr: 'بالاو', dial: '680' },
  { iso: 'PY', nameAr: 'باراغواي', dial: '595' },
  { iso: 'RE', nameAr: 'ريونيون', dial: '262' },
  { iso: 'RS', nameAr: 'صربيا', dial: '381' },
  { iso: 'RW', nameAr: 'رواندا', dial: '250' },
  { iso: 'SB', nameAr: 'جزر سليمان', dial: '677' },
  { iso: 'SC', nameAr: 'سيشل', dial: '248' },
  { iso: 'SG', nameAr: 'سنغافورة', dial: '65' },
  { iso: 'SH', nameAr: 'سانت هيلينا', dial: '290' },
  { iso: 'SI', nameAr: 'سلوفينيا', dial: '386' },
  { iso: 'SJ', nameAr: 'سفالبارد وجان ماين', dial: '47' },
  { iso: 'SK', nameAr: 'سلوفاكيا', dial: '421' },
  { iso: 'SL', nameAr: 'سيراليون', dial: '232' },
  { iso: 'SM', nameAr: 'سان مارينو', dial: '378' },
  { iso: 'SN', nameAr: 'السنغال', dial: '221' },
  { iso: 'SR', nameAr: 'سورينام', dial: '597' },
  { iso: 'SS', nameAr: 'جنوب السودان', dial: '211' },
  { iso: 'ST', nameAr: 'ساو تومي وبرينسيبي', dial: '239' },
  { iso: 'SV', nameAr: 'السلفادور', dial: '503' },
  { iso: 'SX', nameAr: 'سانت مارتن الهولندية', dial: '1' },
  { iso: 'SZ', nameAr: 'إسواتيني', dial: '268' },
  { iso: 'TC', nameAr: 'جزر تركس وكايكوس', dial: '1' },
  { iso: 'TD', nameAr: 'تشاد', dial: '235' },
  { iso: 'TF', nameAr: 'الأراضي الفرنسية الجنوبية', dial: '262' },
  { iso: 'TG', nameAr: 'توغو', dial: '228' },
  { iso: 'TH', nameAr: 'تايلاند', dial: '66' },
  { iso: 'TJ', nameAr: 'طاجيكستان', dial: '992' },
  { iso: 'TK', nameAr: 'توكيلاو', dial: '690' },
  { iso: 'TL', nameAr: 'تيمور الشرقية', dial: '670' },
  { iso: 'TM', nameAr: 'تركمانستان', dial: '993' },
  { iso: 'TO', nameAr: 'تونغا', dial: '676' },
  { iso: 'TT', nameAr: 'ترينيداد وتوباغو', dial: '1' },
  { iso: 'TV', nameAr: 'توفالو', dial: '688' },
  { iso: 'TW', nameAr: 'تايوان', dial: '886' },
  { iso: 'TZ', nameAr: 'تنزانيا', dial: '255' },
  { iso: 'UG', nameAr: 'أوغندا', dial: '256' },
  { iso: 'UM', nameAr: 'جزر الولايات المتحدة النائية', dial: '1' },
  { iso: 'UY', nameAr: 'أوروغواي', dial: '598' },
  { iso: 'UZ', nameAr: 'أوزبكستان', dial: '998' },
  { iso: 'VA', nameAr: 'الفاتيكان', dial: '39' },
  { iso: 'VC', nameAr: 'سانت فينسنت والغرينادين', dial: '1' },
  { iso: 'VE', nameAr: 'فنزويلا', dial: '58' },
  { iso: 'VG', nameAr: 'جزر العذراء البريطانية', dial: '1' },
  { iso: 'VI', nameAr: 'جزر العذراء الأمريكية', dial: '1' },
  { iso: 'VN', nameAr: 'فيتنام', dial: '84' },
  { iso: 'VU', nameAr: 'فانواتو', dial: '678' },
  { iso: 'WF', nameAr: 'واليس وفوتونا', dial: '681' },
  { iso: 'WS', nameAr: 'ساموا', dial: '685' },
  { iso: 'XK', nameAr: 'كوسوفو', dial: '383' },
  { iso: 'YT', nameAr: 'مايوت', dial: '262' },
  { iso: 'ZA', nameAr: 'جنوب أفريقيا', dial: '27' },
  { iso: 'ZM', nameAr: 'زامبيا', dial: '260' },
  { iso: 'ZW', nameAr: 'زيمبابوي', dial: '263' },
];

export const COUNTRY_DIAL_CODES: readonly CountryDialCode[] = [
  DEFAULT_COUNTRY,
  ...COUNTRY_SEEDS.map((seed) => ({ ...seed, flag: flagFromIso(seed.iso) })),
];

const COUNTRY_BY_ISO: ReadonlyMap<string, CountryDialCode> = new Map(
  COUNTRY_DIAL_CODES.map((country) => [country.iso, country])
);

/** Resolves an ISO 3166-1 alpha-2 code (case-insensitive) to its dial-code entry. */
export function getCountryByIso(iso: string | null | undefined): CountryDialCode | null {
  if (!iso) return null;
  return COUNTRY_BY_ISO.get(iso.toUpperCase()) ?? null;
}
