import type {
  AvailabilitySlot,
  ConsultationBooking,
  ConsultationBookingStatus,
  ConsultationPackage,
  ConsultationSettings,
  CreateBookingInput,
  PackageUpsertInput,
  SlotCreateInput,
} from '@/shared/contracts/consultation';

export interface AdminAvailabilitySlot extends AvailabilitySlot {
  /** Booking currently holding this slot, if any. */
  active_booking_id: string | null;
}

// ------------------------------------------------------------
// Packages
// ------------------------------------------------------------

export interface ConsultationPackagesReader {
  listActive(): Promise<ConsultationPackage[]>;
  listAll(): Promise<ConsultationPackage[]>;
  getById(id: string): Promise<ConsultationPackage | null>;
}

export interface ConsultationPackagesWriter {
  create(input: PackageUpsertInput): Promise<ConsultationPackage>;
  update(id: string, input: PackageUpsertInput): Promise<ConsultationPackage>;
  /** Hard-deletes; the FK from historical bookings blocks it when they exist. */
  remove(id: string): Promise<void>;
}

// ------------------------------------------------------------
// Slots
// ------------------------------------------------------------

export interface AvailabilitySlotsReader {
  /** Future slots not held by an active booking. */
  listAvailable(nowIso: string): Promise<AvailabilitySlot[]>;
  /** Every slot from `fromIso` onward with its active-reservation info. */
  listFrom(fromIso: string): Promise<AdminAvailabilitySlot[]>;
}

export interface AvailabilitySlotsWriter {
  create(input: SlotCreateInput): Promise<AvailabilitySlot>;
  /** The DB trigger refuses deletion while an active reservation exists. */
  remove(id: string): Promise<void>;
}

// ------------------------------------------------------------
// Bookings
// ------------------------------------------------------------

export interface BookingListResult {
  data: ConsultationBooking[];
  total: number;
}

export interface ConsultationBookingsReader {
  listForAdmin(
    page: number,
    pageSize: number,
    status?: ConsultationBookingStatus
  ): Promise<BookingListResult>;
}

export interface CreateBookingCommand extends CreateBookingInput {
  /** Opportunistic attribution when a session happens to exist; normally NULL. */
  userId: string | null;
  /** Generated by the service; the column is UNIQUE so collisions are retried. */
  referenceCode: string;
  /** Not collected today; kept nullable for a future optional field. */
  email: string | null;
}

export interface ConsultationBookingsWriter {
  /** Atomic RPC insert of the header + N slot links. Returns the booking id. */
  create(command: CreateBookingCommand): Promise<string>;
  confirm(bookingId: string): Promise<void>;
  reject(bookingId: string, reason?: string): Promise<void>;
}

// ------------------------------------------------------------
// Settings
// ------------------------------------------------------------

export interface ConsultationSettingsReader {
  read(): Promise<Partial<ConsultationSettings>>;
}

export interface ConsultationSettingsWriter {
  upsert(entries: Partial<ConsultationSettings>): Promise<void>;
}
