import type {
  AvailabilitySlot,
  ConsultationBooking,
  ConsultationBookingStatus,
  ConsultationPackage,
  ConsultationSettings,
  CreateBookingInput,
  PackageUpsertInput,
  SlotCreateInput,
} from '@/shared/contracts/consultation';

export interface AdminAvailabilitySlot extends AvailabilitySlot {
  /** Booking currently holding this slot, if any. */
  active_booking_id: string | null;
}

// ------------------------------------------------------------
// Packages
// ------------------------------------------------------------

export interface ConsultationPackagesReader {
  listActive(): Promise<ConsultationPackage[]>;
  listAll(): Promise<ConsultationPackage[]>;
  getById(id: string): Promise<ConsultationPackage | null>;
}

export interface ConsultationPackagesWriter {
  create(input: PackageUpsertInput): Promise<ConsultationPackage>;
  update(id: string, input: PackageUpsertInput): Promise<ConsultationPackage>;
  /** Hard-deletes; the FK from historical bookings blocks it when they exist. */
  remove(id: string): Promise<void>;
}

// ------------------------------------------------------------
// Slots
// ------------------------------------------------------------

export interface AvailabilitySlotsReader {
  /** Future slots not held by an active booking. */
  listAvailable(nowIso: string): Promise<AvailabilitySlot[]>;
  /** Every slot from `fromIso` onward with its active-reservation info. */
  listFrom(fromIso: string): Promise<AdminAvailabilitySlot[]>;
}

export interface AvailabilitySlotsWriter {
  create(input: SlotCreateInput): Promise<AvailabilitySlot>;
  /** The DB trigger refuses deletion while an active reservation exists. */
  remove(id: string): Promise<void>;
}

// ------------------------------------------------------------
// Bookings
// ------------------------------------------------------------

export interface BookingListResult {
  data: ConsultationBooking[];
  total: number;
}

/**
 * The visitor-owned fields a booker may replace on their own booking, plus an
 * optional reschedule. When `slot_ids`/`package_id` are absent only the text is
 * rewritten; when present the holds move through the reschedule RPC.
 */
export interface BookingOwnedEdit {
  full_name: string;
  phone_whatsapp: string;
  email: string | null;
  topic_description: string;
  package_id?: string;
  slot_ids?: string[];
}

export interface ConsultationBookingsReader {
  listForAdmin(
    page: number,
    pageSize: number,
    status?: ConsultationBookingStatus
  ): Promise<BookingListResult>;
  /** The bookings attributed to one signed-in booker, newest first, with sessions. */
  listByUser(userId: string): Promise<ConsultationBooking[]>;
}

export interface CreateBookingCommand extends CreateBookingInput {
  /** Opportunistic attribution when a session happens to exist; normally NULL. */
  userId: string | null;
  /** Generated by the service; the column is UNIQUE so collisions are retried. */
  referenceCode: string;
  /** Not collected today; kept nullable for a future optional field. */
  email: string | null;
}

export interface ConsultationBookingsWriter {
  /** Atomic RPC insert of the header + N slot links. Returns the booking id. */
  create(command: CreateBookingCommand): Promise<string>;
  confirm(bookingId: string): Promise<void>;
  reject(bookingId: string, reason?: string): Promise<void>;
  /**
   * Rewrites the visitor fields of a booking the booker owns, stamping
   * `edited_at`. Ownership is enforced by the write predicate (`user_id`).
   * Returns `null` when no owned row matched.
   */
  updateContactOwned(
    bookingId: string,
    userId: string,
    edit: Pick<BookingOwnedEdit, 'full_name' | 'phone_whatsapp' | 'email' | 'topic_description'>
  ): Promise<ConsultationBooking | null>;
  /**
   * Atomically swaps the package and/or the slot holds in the
   * `reschedule_consultation_booking` RPC, which checks `auth.uid()` against
   * the booking owner. Throws the same codes as creation on failure.
   */
  reschedule(bookingId: string, packageId: string, slotIds: string[]): Promise<void>;
}

// ------------------------------------------------------------
// Settings
// ------------------------------------------------------------

export interface ConsultationSettingsReader {
  read(): Promise<Partial<ConsultationSettings>>;
}

export interface ConsultationSettingsWriter {
  upsert(entries: Partial<ConsultationSettings>): Promise<void>;
}
