import { createClient, SupabaseClient } from '@supabase/supabase-js';

let publicSupabaseInstance: SupabaseClient | null = null;
let adminSupabaseInstance: SupabaseClient | null = null;

/**
 * Gets a Supabase Client configured with public anonymous keys.
 * Fails gracefully on first use if credentials are missing.
 */
export function getPublicSupabase(): SupabaseClient {
  if (!publicSupabaseInstance) {
    const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
    const key = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;

    if (!url || !key) {
      throw new Error(
        'Supabase configuration missing. Please ensure NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY environment variables are set.'
      );
    }

    publicSupabaseInstance = createClient(url, key, {
      auth: {
        persistSession: false,
      },
    });
  }
  return publicSupabaseInstance;
}

/**
 * Gets a Supabase Client configured with the admin service role key to bypass RLS safely on the server side.
 * Fails gracefully on first use if credentials are missing.
 */
export function getAdminSupabase(): SupabaseClient {
  if (!adminSupabaseInstance) {
    const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
    const key = process.env.SUPABASE_SERVICE_ROLE_KEY;

    if (!url || !key) {
      throw new Error(
        'Supabase admin configuration missing. Please ensure NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are set.'
      );
    }

    adminSupabaseInstance = createClient(url, key, {
      auth: {
        persistSession: false,
      },
    });
  }
  return adminSupabaseInstance;
}

let browserSupabaseInstance: SupabaseClient | null = null;

/**
 * Gets a singleton Supabase Client for use in browser components.
 * Uses NEXT_PUBLIC_* environment variables which are available at runtime in the browser.
 *
 * Note: persistSession: true is required for the PKCE OAuth flow —
 * the code_verifier generated by signInWithOAuth() must survive the
 * redirect to Google and back. With persistSession: true, Supabase
 * stores it in localStorage under its own key (sb-<ref>-auth-token).
 * This key is unrelated to the app's own linksnap_* keys.
 */
export function getBrowserSupabase(): SupabaseClient {
  if (!browserSupabaseInstance) {
    const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
    const key = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;

    if (!url || !key) {
      throw new Error(
        'Supabase browser configuration missing. Please ensure NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY are set.'
      );
    }

    browserSupabaseInstance = createClient(url, key, {
      auth: {
        persistSession: true,
      },
    });
  }
  return browserSupabaseInstance;
}

/**
 * Helper to get a Supabase Client authenticated with a user's JWT.
 * This is used to query Supabase on behalf of a specific logged-in user.
 */
export function getUserSupabase(userJwt: string): SupabaseClient {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const anonKey = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;

  if (!url || !anonKey) {
    throw new Error(
      'Supabase configuration missing. Please ensure NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY environment variables are set.'
    );
  }

  // Create a new client instance configured with the user's specific bearer token
  return createClient(url, anonKey, {
    auth: {
      persistSession: false,
    },
    global: {
      headers: {
        Authorization: `Bearer ${userJwt}`,
      },
    },
  });
}
