import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { git, latestSemverTag } from './git-utils.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUTPUT = resolve(ROOT, 'backend', 'config', 'generated', 'app-version.ts');

function readPackageVersion() {
  try {
    const pkg = JSON.parse(readFileSync(resolve(ROOT, 'package.json'), 'utf8'));
    return typeof pkg.version === 'string' && pkg.version ? pkg.version : '0.0.0';
  } catch {
    return '0.0.0';
  }
}

/**
 * Resolves the release version string in a fully deterministic way, tolerating
 * the absence of git and never mutating the repository.
 */
export function resolveReleaseVersion({ appVersionOverride, packageVersion, commitSha, count }) {
  const semver = appVersionOverride || packageVersion;
  const sha7 = (commitSha || '').slice(0, 7) || 'unknown';
  const releaseVersion = `${semver}+build.${count}.${sha7}`;
  return {
    releaseVersion,
    semver,
    commit: commitSha || 'unknown',
    ref: 'unknown',
    env: 'development',
    releasedAt: new Date().toISOString(),
  };
}

/**
 * Decides whether regenerating app-version.ts may touch the working tree.
 * CI providers (GitHub Actions sets CI=true; Vercel sets CI/VERCEL=1) always
 * write so the release pipeline is unaffected. Local dev/build skips the
 * write, keeping the committed default (and `git status`) pristine.
 * APP_VERSION_WRITE=force|skip overrides either way.
 */
export function shouldWriteAppVersion(env = process.env) {
  if (env.APP_VERSION_WRITE === 'force') return true;
  if (env.APP_VERSION_WRITE === 'skip') return false;
  const ci = String(env.CI ?? '')
    .trim()
    .toLowerCase();
  return (
    ci === 'true' ||
    ci === '1' ||
    env.VERCEL === '1' ||
    Boolean(env.VERCEL_ENV) ||
    Boolean(env.VERCEL_GIT_COMMIT_SHA)
  );
}

export function main() {
  const appVersionOverride = process.env.APP_VERSION || undefined;
  const packageVersion = readPackageVersion();
  const lastTag = latestSemverTag();
  const count = lastTag ? git(['rev-list', '--count', `${lastTag}..HEAD`], '0') : '0';
  const commitSha = process.env.VERCEL_GIT_COMMIT_SHA || git(['rev-parse', 'HEAD'], '');

  const resolved = resolveReleaseVersion({
    appVersionOverride,
    packageVersion,
    commitSha: commitSha || undefined,
    count,
  });

  resolved.ref =
    process.env.VERCEL_GIT_COMMIT_REF || git(['symbolic-ref', '--short', 'HEAD'], '') || 'unknown';
  resolved.env = process.env.VERCEL_ENV || 'development';

  const content =
    '// Auto-generated by scripts/compute-version.mjs — do not edit by hand.\n' +
    '// Regenerated by prebuild/predev on CI and Vercel only; locals use the\n' +
    '// committed default (override with APP_VERSION_WRITE=force).\n' +
    'export const appVersion = {\n' +
    `  releaseVersion: '${resolved.releaseVersion}',\n` +
    `  semver: '${resolved.semver}',\n` +
    `  commit: '${resolved.commit}',\n` +
    `  ref: '${resolved.ref}',\n` +
    `  env: '${resolved.env}',\n` +
    `  releasedAt: '${resolved.releasedAt}',\n` +
    '} as const;\n';

  let existing;
  try {
    existing = readFileSync(OUTPUT, 'utf8');
  } catch {
    // Missing file (fresh checkout variant) — always generate so tsc/tests work.
  }

  // Skip silently when running outside CI/Vercel and the committed default exists.
  if (existing !== undefined && !shouldWriteAppVersion()) {
    return resolved;
  }
  if (existing === content) {
    return resolved;
  }

  mkdirSync(dirname(OUTPUT), { recursive: true });
  writeFileSync(OUTPUT, content, 'utf8');
  return resolved;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main();
}
